### ISSUE TITLE
Issue with user

### ISSUE THREAD

**Issue by extreme-edge-x** [target111/py-onym#2]
Hello, very interested in your script, I tried following your instructions, installed the dependencies, made sure chromedriver works, however I keep getting this error:

C:\Users\Admin\Desktop\py-onym-master>python tellonym.py bitchlasagna.txt -t 100 -r 10 myname
usage: tellonym.py [-h] [-i INPUT_FILE] [-t TIMES] [-r RETRIES] user
tellonym.py: error: unrecognized arguments: myname

Tried it with different usernames, however console wont accept anything, however it "launches" if I leave user field blank and enter, it prompts that application is working however nothing is happening . Any ideas?

Regards.

**Comment by target111** [comment]
Those problems come from the fact that you didn't specify the input file with the ```-i``` flag, so the script treats ```bitchlasagna.txt``` as the user. After that, it either errors in the first scenario because it thinks you've provided two users, or in case you remove the user, nothing happens because you didn't provide any input and so it's waiting to get it from stdin.

The fix would be to launch the application correctly like this:
```python tellonym.py -i bitchlasagna.txt -t 1000 -r 100 your_user```

**Comment by extreme-edge-x** [comment]
Thank you for your answer. However I encountered another problem:

DevTools listening on ws://127.0.0.1:53080/devtools/browser/009ed35b-721a-432e-8e47-bd222e135bf3
19-Jun-20 18:22:01 - Sending message: 'test message'
[0619/182204.386:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.", source: https://tellonym.me/faggot99 (0)
[0619/182207.574:INFO:CONSOLE(6)] "The PerformanceObserver does not support buffered flag with the entryTypes argument.", source: https://securepubads.g.doubleclick.net/tag/js/gpt.js (6)
[0619/182209.638:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://bidswitch.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.", source: https://tellonym.me/faggot99 (0)
[0619/182209.921:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://contextweb.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.", source: https://tellonym.me/faggot99 (0)
Traceback (most recent call last):
  File "tellonym.py", line 111, in <module>
    main()
  File "tellonym.py", line 107, in main
    run(parse_args())
  File "tellonym.py", line 81, in run
    if tellonym.send(message):
  File "tellonym.py", line 23, in send
    self.s.handle_popup()
  File "C:\Users\Admin\Desktop\py-onym-master\lib\service.py", line 28, in handle_popup
    self.wait_element_present((By.CLASS_NAME, CLASS_NAME_BUTTON),
  File "C:\Users\Admin\Desktop\py-onym-master\lib\service.py", line 55, in wait_element_present
    wait.until(expected_conditions.presence_of_element_located(locator))
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

Any ideas?

**Comment by target111** [comment]
Probably your internet connection isn't strong enough in which case you will have to increase the timeout. I've pushed a new commit that let's you easily do that via the `--timeout` flag. Run git pull or download a new zip of the repo and try again with that version and with the new flag.

**Comment by target111** [comment]
Nevermind my previous comment, the actual problem was coming from the fact they they updated their website and so the buttons the script had to press were no longer the ones it knew. I have now fixed it, so you should definitely pull to get the newest commits. I also added a firefox driver in `config/` so it you want to use that, all you have to do is edit `lib/service.py` on line 10 to import `config.firefox` instead of `config.chrome`. This is entirely optional though, so if you already have chrome setup, don't do this. Hope you won't have anymore issues with the program! :)

**Comment by extreme-edge-x** [comment]
Thank you again for your reply and your time target111 here are my results:

python tellonym.py -i bitchlasagna.txt -t 100 -r 10 --timeout 120 testmember00
20-Jun-20 17:24:38 - Starting Tellonym Spammer application.
20-Jun-20 17:24:43 - Sending message: 'TEST MESSAGE TEST MESSAGE TEST MESSAGE TEST MESSAGE TEST MESSAGE TEST MESSAGE TEST MESSAGE'
Traceback (most recent call last):
  File "tellonym.py", line 122, in <module>
    main()
  File "tellonym.py", line 118, in main
    run(parse_args())
  File "tellonym.py", line 92, in run
    if tellonym.send(message):
  File "tellonym.py", line 27, in send
    self.s.handle_popup()
  File "C:\Users\Admin\Desktop\py-onym-master\lib\service.py", line 28, in handle_popup
    self.wait_element_present((By.CLASS_NAME, CLASS_NAME_BUTTON))
  File "C:\Users\Admin\Desktop\py-onym-master\lib\service.py", line 54, in wait_element_present
    wait.until(expected_conditions.presence_of_element_located(locator))
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

This time I tried with Firefox with geckodriver because Chrome still was giving me errors with cookies and `Samesite`. Tried running it with a timeout of 120, however my internet is stable with 200 /10 mb sec and ping to google.com with 30 ms. However still there is something wrong.

**Comment by target111** [comment]
Are you on the `d31c2bb76d915e3693576e5d6394d9bf37069a74` commit? Make sure the button line in `lib/constants.py` matches `CLASS_NAME_BUTTON = "banner_continue--2NyXA"` . If it does, then try commenting the headless line in `firefox.py` or `chrome.py` . This will open a visible browser window when you run it, so let me know if it gets past the allow cookies or whatever popup.

**Comment by extreme-edge-x** [comment]
Yes, I am on your latest commit. The button line matches with `CLASS_NAME_BUTTON = "banner_continue--2NyXA"` .

I am sorry, I am a bit new to Python, how exactly do I "commenting the headless line in firefox.py or chrome.py"

Thank you.

**Comment by target111** [comment]
Add a `#` at the start of the line that contains `'--headless'` in either `firefox.py` or `chrome.py`.

**Comment by extreme-edge-x** [comment]
I have recorded the behaviors so you can have a better understanding.  

https://streamable.com/dl8uwo - Chrome
https://streamable.com/qo2ogi - Firefox

**Comment by target111** [comment]
Oh, I see what's happening, I'm gonna try and fix it today.

**Comment by target111** [comment]
Can you open `tellonym.py` and comment out line 27 - the one with `self.s.handle_popup()` and let me know if it works, untill I make a better solution?

**Comment by extreme-edge-x** [comment]
Yes, that works correctly. How can I control how many messages it sends per minute?

Thank you.

**Comment by target111** [comment]
You can modify the `sleep_random()` parameters on line 43 in `lib/service.py` to change the timing. First integer represents the minimum number of seconds to sleep after each messages and the second, that max number of seconds to sleep. Doing something like `sleep_random(30, 31)` should make the program send two messages / minute.

**Comment by extreme-edge-x** [comment]
Yes that works, however when you extend that pause time, the script will keep trying to send the first line of the source, thinking it failed to send it, when in reality it was successfully sent. So it just keeps on sending the first line and looks like tellonym has some sort of anti spam that discards too many same messages (not 100% confirmed).

24-Jun-20 15:51:34 - Failed to send message. Retrying...
Pausing execution flow for 30.20499824342115 seconds...
24-Jun-20 15:52:05 - Failed to send message. Retrying...
Pausing execution flow for 30.089490294626977 seconds...
24-Jun-20 15:52:36 - Failed to send message. Retrying...
Pausing execution flow for 30.987468233951578 seconds...
24-Jun-20 15:53:08 - Failed to send message. Retrying...

**Comment by Poppy3** [comment]
Hi! I downloaded the code and run it with pycharm. I get what you wrote in the last comment, the "failed to send message" for every try but instead it does not sent the first message. Is it a problem with pycharm maybe? For testing purposes I only have one line in the input-text.txt file, but I don't think this is the problem here.
Chromedriver and everything looks okay, I don't get any other error.

15-Jul-20 11:19:04 - Starting Tellonym Spammer application.
15-Jul-20 11:19:07 - Sending message: 'My message - test'
Pausing execution flow for 1.1810423010323405 seconds...
15-Jul-20 11:19:12 - Failed to send message. Retrying...
Pausing execution flow for 1.213265175304007 seconds...
15-Jul-20 11:19:16 - Failed to send message. Retrying...
Pausing execution flow for 1.8199620825031833 seconds...
15-Jul-20 11:19:20 - Failed to send message. Retrying...
Pausing execution flow for 1.0287032072332345 seconds...
15-Jul-20 11:19:24 - Failed to send message. Retrying...
Pausing execution flow for 1.9598474195714655 seconds...
15-Jul-20 11:19:28 - Failed to send message. Retrying...
Pausing execution flow for 1.737943710157239 seconds...
15-Jul-20 11:19:32 - Failed to send message. Retrying...
Pausing execution flow for 1.8489034083242066 seconds...
15-Jul-20 11:19:36 - Failed to send message. Retrying...
Pausing execution flow for 1.5714076791542095 seconds...
15-Jul-20 11:19:40 - Failed to send message. Retrying...
Pausing execution flow for 1.5870125593312168 seconds...
15-Jul-20 11:19:44 - Failed to send message. Retrying...
Pausing execution flow for 1.1138302211602522 seconds...
15-Jul-20 11:19:47 - Failed to send message. Retrying...
Pausing execution flow for 1.1436524440350153 seconds...
15-Jul-20 11:19:50 - Failed to send message. Retrying...
Pausing execution flow for 1.1802882772831182 seconds...
15-Jul-20 11:19:53 - Max retries exceeded. Giving up.

Process finished with exit code 1

**Comment by extreme-edge-x** [comment]
@Poppy3 yes that works fine with a small time pause like 1-3 seconds. Try running with something like 30 second pause between the messages and the application will keep sending the first line of the text source.

**Comment by extreme-edge-x** [comment]
@Poppy3 working with chrome gave me many weird problems, with firefox it was much smoother.

**Comment by hypersquid** [comment]
Hey I'm having an issue. I'm doing python3 tellonym.py -i message2.txt -t 1000 -r 100 -r 10 --timeout 120  acashaderoom

and I get
03-Sep-20 21:09:27 - Starting Tellonym Spammer application.
Traceback (most recent call last):
  File "/home/oem/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tellonym.py", line 122, in <module>
    main()
  File "tellonym.py", line 118, in main
    run(parse_args())
  File "tellonym.py", line 83, in run
    tellonym = Tellonym(args.user, args.timeout)
  File "tellonym.py", line 21, in __init__
    self.s = Service(url=PAGE_URL + self.user, default_timeout=self.timeout)
  File "/home/oem/Downloads/py-onym-master/lib/service.py", line 21, in __init__
    self.driver = get_driver_config()
  File "/home/oem/Downloads/py-onym-master/config/chrome.py", line 18, in get_driver_config
    driver = webdriver.Chrome(options=options)
  File "/home/oem/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/oem/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by target111** [comment]
> Can you open `tellonym.py` and comment out line 27 - the one with `self.s.handle_popup()` and let me know if it works, untill I make a better solution?

    As you can see in the error, it says you need to install chromedriver(it's like an interface between this script and your browser) and even gives you a link from where you can download.

**Comment by target111** [comment]
> Can you open `tellonym.py` and comment out line 27 - the one with `self.s.handle_popup()` and let me know if it works, untill I make a better solution?

As you can see in the error, it says you need to install chromedriver(it's like an interface between this script and your browser) and even gives you a link from where you can download it. If you need further clarification [here's](https://zwbetz.com/download-chromedriver-binary-and-add-to-your-path-for-automated-functional-testing/#windows) a link that can help you.

**Comment by target111** [comment]
> Hey I'm having an issue. I'm doing python3 tellonym.py -i message2.txt -t 1000 -r 100 -r 10 --timeout 120 acashaderoom
> 
> and I get
> 03-Sep-20 21:09:27 - Starting Tellonym Spammer application.
> Traceback (most recent call last):
> File "/home/oem/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
> stdin=PIPE)
> File "/usr/lib/python3.6/subprocess.py", line 729, in **init**
> restore_signals, start_new_session)
> File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "tellonym.py", line 122, in
> main()
> File "tellonym.py", line 118, in main
> run(parse_args())
> File "tellonym.py", line 83, in run
> tellonym = Tellonym(args.user, args.timeout)
> File "tellonym.py", line 21, in **init**
> self.s = Service(url=PAGE_URL + self.user, default_timeout=self.timeout)
> File "/home/oem/Downloads/py-onym-master/lib/service.py", line 21, in **init**
> self.driver = get_driver_config()
> File "/home/oem/Downloads/py-onym-master/config/chrome.py", line 18, in get_driver_config
> driver = webdriver.Chrome(options=options)
> File "/home/oem/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in **init**
> self.service.start()
> File "/home/oem/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
> os.path.basename(self.path), self.start_error_message)
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

As you can see in the error, it says you need to install chromedriver(it's like an interface between this script and your browser) and even gives you a link from where you can download it. If you need further clarification [here's](https://zwbetz.com/download-chromedriver-binary-and-add-to-your-path-for-automated-functional-testing/#windows) a link that can help you.

**Comment by target111** [comment]
> Yes that works, however when you extend that pause time, the script will keep trying to send the first line of the source, thinking it failed to send it, when in reality it was successfully sent. So it just keeps on sending the first line and looks like tellonym has some sort of anti spam that discards too many same messages (not 100% confirmed).
> 
> 24-Jun-20 15:51:34 - Failed to send message. Retrying...
> Pausing execution flow for 30.20499824342115 seconds...
> 24-Jun-20 15:52:05 - Failed to send message. Retrying...
> Pausing execution flow for 30.089490294626977 seconds...
> 24-Jun-20 15:52:36 - Failed to send message. Retrying...
> Pausing execution flow for 30.987468233951578 seconds...
> 24-Jun-20 15:53:08 - Failed to send message. Retrying...

Sorry this took so long, I have added a proper option for controlling the rate of messages, along with better verifcation that the message was sent successfully and fixed cookie pop-up validation.

**Comment by target111** [comment]
> Hi! I downloaded the code and run it with pycharm. I get what you wrote in the last comment, the "failed to send message" for every try but instead it does not sent the first message. Is it a problem with pycharm maybe? For testing purposes I only have one line in the input-text.txt file, but I don't think this is the problem here.
> Chromedriver and everything looks okay, I don't get any other error.
> 
> 15-Jul-20 11:19:04 - Starting Tellonym Spammer application.
> 15-Jul-20 11:19:07 - Sending message: 'My message - test'
> Pausing execution flow for 1.1810423010323405 seconds...
> 15-Jul-20 11:19:12 - Failed to send message. Retrying...
> Pausing execution flow for 1.213265175304007 seconds...
> 15-Jul-20 11:19:16 - Failed to send message. Retrying...
> Pausing execution flow for 1.8199620825031833 seconds...
> 15-Jul-20 11:19:20 - Failed to send message. Retrying...
> Pausing execution flow for 1.0287032072332345 seconds...
> 15-Jul-20 11:19:24 - Failed to send message. Retrying...
> Pausing execution flow for 1.9598474195714655 seconds...
> 15-Jul-20 11:19:28 - Failed to send message. Retrying...
> Pausing execution flow for 1.737943710157239 seconds...
> 15-Jul-20 11:19:32 - Failed to send message. Retrying...
> Pausing execution flow for 1.8489034083242066 seconds...
> 15-Jul-20 11:19:36 - Failed to send message. Retrying...
> Pausing execution flow for 1.5714076791542095 seconds...
> 15-Jul-20 11:19:40 - Failed to send message. Retrying...
> Pausing execution flow for 1.5870125593312168 seconds...
> 15-Jul-20 11:19:44 - Failed to send message. Retrying...
> Pausing execution flow for 1.1138302211602522 seconds...
> 15-Jul-20 11:19:47 - Failed to send message. Retrying...
> Pausing execution flow for 1.1436524440350153 seconds...
> 15-Jul-20 11:19:50 - Failed to send message. Retrying...
> Pausing execution flow for 1.1802882772831182 seconds...
> 15-Jul-20 11:19:53 - Max retries exceeded. Giving up.
> 
> Process finished with exit code 1

verifying that the message was sent successfully has been improved by a lot, all should be good now
