### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Suspect11** [target111/py-onym#3]
hello is this still down? is there gonna be a fix for the issue?

**Comment by target111** [comment]
What issue are you experiencing?

**Comment by Suspect11** [comment]
File "tellonym.py", line 122, in <module>
    main()
  File "tellonym.py", line 118, in main
    run(parse_args())
  File "tellonym.py", line 92, in run
    if tellonym.send(message):
  File "tellonym.py", line 27, in send
    self.s.handle_popup()
  File "C:\Users\Desktop\py-onym\lib\service.py", line 28, in handle_popup
    self.wait_element_present((By.CLASS_NAME, CLASS_NAME_BUTTON))
  File "C:\Users\\Desktop\py-onym\lib\service.py", line 54, in wait_element_present
    wait.until(expected_conditions.presence_of_element_located(locator))
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Suspect11** [comment]
and can u message me on discord or somethign else so we can finish this faster?

**Comment by target111** [comment]
Try editing ```tellonym.py``` and comment out line 27 - the one with ```self.s.handle_popup()```.  For some users, the accept cookies pop-up doesn't appear and so the program hangs, waiting for that event. I'll make fix later. Let me know if it works

**Comment by Suspect11** [comment]
if not self.cookies:
            self.s.handle_popup()
            self.cookies = True

**Comment by Suspect11** [comment]
line 17:def __init__(self, user, timeout):
        self.cookies = False
line 27: if not self.cookies:
            self.s.handle_popup()
            self.cookies = True                 i feel like smt wrong here

**Comment by target111** [comment]
You need to add a ```#``` at the beginning on line 27. That's how you comment stuff out in python.

**Comment by target111** [comment]
Line 27 should be the one with ```self.s.handle_popup()```. Just add a ```#``` at the beginning of that line.

**Comment by Suspect11** [comment]
damm bro that was easy u should update it so no one gotta make issues ilyk if anything else happens

**Comment by target111** [comment]
I'm glad it works
