### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ghost** [target111/py-onym#9]
hello, i have problem.. well it's reporting unresolved import 
![image](https://user-images.githubusercontent.com/86264047/122825614-773f2180-d2e2-11eb-9f15-f9265bf4c359.png)
i am totally clueless, i was browsing few webs, but i couldn't find any help

useless info: i will go on programming high school so if it's okay, could you please tell me details about this?

**Comment by target111** [comment]
That's weird, I'm not entirely sure what IDE you're using but it's reporting that it couldn't load any files from the `lib` directory which contains the main script files. Probably some path issues. Try running it from the terminal.

**Comment by target111** [comment]
You can try creating an empty `__init__.py` file in the `lib` directory.

**Comment by ghost** [comment]
no, sorry, it's not working
i'm using Visual Studio 2019
if you want closer info or screenshare, here's my discord: camillia#7537

**Comment by ghost** [comment]
thanks you very much for help and patience it's working as it should
